COS-521 - Fix the input validation test.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -65,6 +65,11 @@ runs:
     - id: input-check
       name: Checking validity of input parameters
       run: |
+        export OUTPUT_FORMAT_REGEX='^(json|markdown|sarif|formatted)(,(json|markdown|sarif|formatted))*$';
+        if [[ ! "${{inputs.outputFormat}}" =~ "$OUTPUT_FORMAT_REGEX" ]]; then
+          echo "Invalid input";
+          exit 1;
+        fi
         test ${{inputs.outputFormat}} = "formatted" -o ${{inputs.outputFormat}} = "sarif" -o ${{inputs.outputFormat}} = "json"
         test ${{inputs.failLevel}} -ge 1 -a ${{inputs.failLevel}} -le 6
       shell: bash
